### ISSUE TITLE
ImportError: cannot import name 'run'

### ISSUE THREAD

**Issue by rrichajalota** [fisadev/virtualbackground#8]
Hello, 

After running the installation instructions, I tried running `python viba.py` but it throws the following error. 
```Traceback (most recent call last):
  File "viba.py", line 3, in <module>
    from asyncio import run, get_running_loop, sleep, gather
ImportError: cannot import name 'run'
```
Any suggestions for fixing it? 

OS: Ubuntu 18.04

**Comment by fisadev** [comment]
Oh! It turns out that `asyncio.run` was added in python 3.7, so the project then requires python 3.7 or higher. I will add this to the README :)

**Comment by fisadev** [comment]
As for suggestions, I would try to install python 3.7 or 3.8, but I don't know if they are available in ubuntu 18.04 official repos. You might need to install it by hand, or using a ppa.

**Comment by rrichajalota** [comment]
Hi @fisadev, it works with python3.8 but now I face another issue. When I run `python viba.py --use-gpu --real-cam-device /dev/video2 --fake-cam-device /dev/video20`, I only see a black screen on running a webcam application. In Cheese, it says 'There was an error playing video from the webcam' and on MS Teams, I only see a black screen. Any idea, why?
